server:
   port: 8081

spring:
   application:
      name: weather-catalogue
   profiles:
      active: eurekaconfig

my_app_weather:
   host: LAPTOP-M1230BFO
   services:
      #areacode: ${my_app_weather.host}:8082/areacode/
      #localweather: ${my_app_weather.host}:8083/localweather/
      areacode: http://weather-area-code-service/areacode/
      localweather: http://weather-service/localweather/
      apiKey: bcb6eaaccc6eca553b655050ec70c845
#api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}

